// Text measurement without font files, from widths generated by
// scripts/font-metrics.ts: Carlito (Calibri's metrics) for every character it
// draws, Noto Sans TC for the symbols Carlito lacks, and one em for CJK
// ideographs and anything neither font has (emoji). The browser and the
// server measure the same way, so they wrap lines identically.
import metrics from "./carlito-metrics.json";

export type FontStyle = { size: number; bold: boolean; italic: boolean };

type Variant = keyof typeof metrics.widths;
type Table = Record<string, number | undefined>;

const UNITS = metrics.unitsPerEm;
const REGULAR = metrics.widths.regular as Table;
const NOTO = metrics.noto.widths as Table;
const NOTO_UNITS = metrics.noto.unitsPerEm;

/** Single line spacing as a multiple of the font size: 1.2207 for Calibri. */
export const LINE_HEIGHT =
  (metrics.ascender - metrics.descender + metrics.lineGap) / UNITS;

/** The baseline's distance below the top of a line, per px of font size. */
export const ASCENT = metrics.ascender / UNITS;

function variant(style: FontStyle): Variant {
  if (style.bold) return style.italic ? "boldItalic" : "bold";
  return style.italic ? "italic" : "regular";
}

/** East Asian wide characters (CJK, kana, Hangul, full-width forms, emoji). */
export function isWide(cp: number): boolean {
  return (
    (cp >= 0x1100 && cp <= 0x115f) ||
    (cp >= 0x2e80 && cp <= 0x303e) ||
    (cp >= 0x3041 && cp <= 0x33ff) ||
    (cp >= 0x3400 && cp <= 0x4dbf) ||
    (cp >= 0x4e00 && cp <= 0x9fff) ||
    (cp >= 0xa960 && cp <= 0xa97f) ||
    (cp >= 0xac00 && cp <= 0xd7a3) ||
    (cp >= 0xf900 && cp <= 0xfaff) ||
    (cp >= 0xfe30 && cp <= 0xfe4f) ||
    (cp >= 0xff00 && cp <= 0xff60) ||
    (cp >= 0xffe0 && cp <= 0xffe6) ||
    (cp >= 0x1f300 && cp <= 0x1faff) ||
    (cp >= 0x20000 && cp <= 0x3fffd)
  );
}

/**
 * The font that draws a character: Carlito when it has the glyph, otherwise
 * the CJK font (Noto Sans TC, or a tofu box of its width).
 */
export function fontOf(cp: number): "latin" | "cjk" {
  return REGULAR[cp] !== undefined ? "latin" : "cjk";
}

/** The advance width of one character, in px. */
export function charWidth(cp: number, style: FontStyle): number {
  if (REGULAR[cp] !== undefined) {
    const units = (metrics.widths[variant(style)] as Table)[cp] ?? REGULAR[cp]!;
    return (units / UNITS) * style.size;
  }
  if (isWide(cp)) return style.size;
  const noto = NOTO[cp];
  return noto === undefined ? style.size : (noto / NOTO_UNITS) * style.size;
}

/** The advance width of a string, in px, without kerning. */
export function measure(text: string, style: FontStyle): number {
  let width = 0;
  for (const ch of text) width += charWidth(ch.codePointAt(0)!, style);
  return width;
}
