// Text measurement without font files: Carlito's advance widths (Calibri's
// metrics, generated by scripts/font-metrics.ts) for Latin, and one em for
// East Asian wide characters, which CJK fonts draw on a square. The browser
// and the server measure the same way, so they wrap lines identically.
import metrics from "./carlito-metrics.json";

export type FontStyle = { size: number; bold: boolean; italic: boolean };

type Variant = keyof typeof metrics.widths;
type Table = Record<string, number | undefined>;

const UNITS = metrics.unitsPerEm;

/** Single line spacing as a multiple of the font size: 1.2207 for Calibri. */
export const LINE_HEIGHT =
  (metrics.ascender - metrics.descender + metrics.lineGap) / UNITS;

/** The baseline's distance below the top of a line, per px of font size. */
export const ASCENT = metrics.ascender / UNITS;

// Characters Carlito has no glyph for fall back to the width of "n".
const FALLBACK = (metrics.widths.regular as Table)["110"] ?? UNITS / 2;

function variant(style: FontStyle): Variant {
  if (style.bold) return style.italic ? "boldItalic" : "bold";
  return style.italic ? "italic" : "regular";
}

/** East Asian wide characters (CJK, kana, Hangul, full-width forms, emoji). */
export function isWide(cp: number): boolean {
  return (
    (cp >= 0x1100 && cp <= 0x115f) ||
    (cp >= 0x2e80 && cp <= 0x303e) ||
    (cp >= 0x3041 && cp <= 0x33ff) ||
    (cp >= 0x3400 && cp <= 0x4dbf) ||
    (cp >= 0x4e00 && cp <= 0x9fff) ||
    (cp >= 0xa960 && cp <= 0xa97f) ||
    (cp >= 0xac00 && cp <= 0xd7a3) ||
    (cp >= 0xf900 && cp <= 0xfaff) ||
    (cp >= 0xfe30 && cp <= 0xfe4f) ||
    (cp >= 0xff00 && cp <= 0xff60) ||
    (cp >= 0xffe0 && cp <= 0xffe6) ||
    (cp >= 0x1f300 && cp <= 0x1faff) ||
    (cp >= 0x20000 && cp <= 0x3fffd)
  );
}

/** The advance width of one character, in px. */
export function charWidth(cp: number, style: FontStyle): number {
  if (isWide(cp)) return style.size;
  const units = (metrics.widths[variant(style)] as Table)[cp] ?? FALLBACK;
  return (units / UNITS) * style.size;
}

/** The advance width of a string, in px, without kerning. */
export function measure(text: string, style: FontStyle): number {
  let width = 0;
  for (const ch of text) width += charWidth(ch.codePointAt(0)!, style);
  return width;
}
