-- Members, decks, their revision history, each member's selection, and the
-- image assets decks point at. Ids are generated by the app (lib/ids.ts).

create table users (
  sub text primary key,                      -- Keycloak subject
  name text not null default '',
  email text not null default '',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table decks (
  id text primary key,
  owner_sub text not null references users (sub),
  title text not null,                       -- mirrors document.title, for lists
  document jsonb not null,                   -- lib/deck/schema.ts
  version integer not null default 0,        -- +1 for every applied revision
  published boolean not null default false,
  public_id text unique,                     -- random, set on first publish
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index decks_owner_updated on decks (owner_sub, updated_at desc);

create table revisions (
  id bigint generated always as identity primary key,
  deck_id text not null references decks (id) on delete cascade,
  base_version integer not null,             -- the deck version the patch was written against
  version integer,                           -- the version it produced; null unless applied
  author_kind text not null check (author_kind in ('member', 'agent')),
  author_sub text not null,                  -- the member, or the member an agent acts for
  status text not null check (status in ('applied', 'suggested', 'rejected')),
  patch jsonb not null,                      -- RFC 6902 operations
  inverse jsonb,                             -- undoes an applied patch
  created_at timestamptz not null default now(),
  check ((status = 'applied') = (version is not null))
);

create index revisions_deck on revisions (deck_id, id desc);

create table selections (
  user_sub text primary key references users (sub) on delete cascade,
  deck_id text references decks (id) on delete cascade,
  slide_id text,
  targets jsonb not null default '[]',       -- [{ shape, text?: [start, end] }]
  updated_at timestamptz not null default now()
);

create table assets (
  sha256 text primary key check (sha256 ~ '^[0-9a-f]{64}$'),
  uploader_sub text not null references users (sub),
  mime text not null,
  bytes integer not null check (bytes > 0),
  width integer,
  height integer,
  created_at timestamptz not null default now()
);
